version: '3.8'

services:
  mysqldb:
    container_name: database
    image: rumesha/contact-hub-db
    restart: always
    ports:
      - 3306:3306
    # networks:
    #   - contact-hub-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
# networks:
#   contact-hub-network