version: '3.8'

services:
  mysqldb:
    container_name: database
    image: rumesha/contact-hub-db
    restart: always
    ports:
      - 3306:3306
    networks:
      - contact-hub-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  frontend:
    container_name: frontend
    image: rumesha/contact-hub-frontend
    restart: always
    ports:
      - 3000:3000
    networks:
      - contact-hub-network
    depends_on:
      - mysqldb
  backend:
    container_name: backend
    restart: always
    image: rumesha/contact-hub-backend
    ports:
      - "8080:8080"
    networks:
      - contact-hub-network
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://database:3306/contact-hub?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "admin",
        "spring.datasource.password" : "admin",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
        }'
networks:
  contact-hub-network: