on:
    push:
        branches:
        - main
        paths: 
        - "database/**"
        - ".github/workflows/deploy-db.yml"
    pull_request:
        types: [opened, synchronize, reopened]
jobs:
    database:
        name: Build Docker Image
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout 
            uses: actions/checkout@master  
            with:
            # Disabling shallow clone is recommended for improving relevancy of reporting
                fetch-depth: 0
        -   name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}
        -   name: Build and push
            uses: docker/build-push-action@v5
            with:
                context: database/
                push: true
                build-args: |
                    - DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
                    - DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
                tags: rumesha/contact-hub-db:latest
    
  